---
# Priority: explicit besu_host_ip > auto-detect based on besu_host_ip_type (public|private)
- name: network | Use private IP
  ansible.builtin.set_fact:
    besu_host_ip: "{{ ansible_default_ipv4.address }}"
  when: besu_host_ip == "" and besu_host_ip_type == "private"

- name: network | Fetch public IP
  ansible.builtin.uri:
    url: http://ifconfig.me/ip
    method: GET
    return_content: yes
    status_code: 200
  register: besu_public_ip_output
  ignore_errors: True
  when: besu_host_ip == "" and besu_host_ip_type == "public"

- name: network | Use public IP
  ansible.builtin.set_fact:
    besu_host_ip: "{{ besu_public_ip_output.content }}"
  when: besu_host_ip == "" and besu_host_ip_type == "public" and besu_public_ip_output.status == 200
