---
- name: darwin | Add Besu Brew tap
  community.general.homebrew_tap:
    name: hyperledger/besu
    state: present

- name: darwin | Install Besu via brew
  community.general.homebrew:
    name: besu
    state: present
